apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: untrusted-binding
  namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: untrusted-pod
subjects:
- kind: ServiceAccount
  name: default
  namespace: demo
